name: GreenTornado Fly.io Build and Deploy
on: 
  push:
    branches:
      - master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      if: "! contains(github.event.head_commit.message, '[ci skip]')"
      steps:
        - uses: actions/checkout@v2

        # - name: Checkout submodules
        #   uses: srt32/git-actions@v0.0.3
        #   with:
        #     args: git submodule update --init --recursive

        - name: Turnstyle
          uses: softprops/turnstyle@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - uses: satackey/action-docker-layer-caching@v0.0.8

        - uses: superfly/flyctl-actions@1.1
          with:
            args: "deploy"

        - uses: sarisia/actions-status-discord@v1.5.2
          with:
            webhook: ${{ secrets.DISCORD_WEBHOOK }}
            status: ${{ job.status }}
            title: "Deployed"
            description: ${{"Commit hash: \`\`" + github.event.commit/message + "\`\`"}}
            nofail: false
            nodetail: false
            color: 0x00ff00
            username: GreenTornado build status
